### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by leasoncre** [EvelynSubarrow/Commandspy#4]
I've never used this plugin before.
Aside from turing command spy on/off i can't figure out how to set it up

can you add some examples of how to use the plugin/commands? 
specifically, the "/commandspy filter" and "/commandspy config" commands. as the commands syntax is usefull, it doesn't tell me what it all means, and how to put it all together.

also, a config.yml with comments describing what each option does would help as well.

i've googled youtube vids and they were not helpful.

**Comment by EvelynSubarrow** [comment]
The documentation is quite frankly abysmal, yeah. The fact that the source
code, as it exists here is a somewhat incomplete total rewrite in a
language most people are unfamiliar with probably isn't helpful. When I
finally manage to motivate myself to complete it, I need to work on the
documentation quite badly.

For what it's worth, the level of customisability available in currently
released versions is somewhat... limited. What are you looking to do?

2015-11-24 21:53 GMT+00:00 leasoncre <notifications@github.com>:

> I've never used this plugin before.
> Aside from turing command spy on/off i can't figure out how to set it up
>
> can you add some examples of how to use the plugin/commands?
> specifically, the "/commandspy filter" and "/commandspy config" commands.
> as the commands syntax is usefull, it doesn't tell me what it all means,
> and how to put it all together.
>
> also, a config.yml with comments describing what each option does would
> help as well.
>
> i've googled youtube vids and they were not helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EvelynSubarrow/Commandspy3/issues/4>.
>



-- 

*kuta li wudema pinume!*

*кута ли юудема пинуме!*

**Comment by leasoncre** [comment]
some stuff off the top of my head:
1+disable console spying for all players EXCEPT those on a 'whitelist' ie: OP'd players for starters
2+ignore specific console commands (globally, &/or per-player). ie: save-on, save-all (happens every 10 min and i can see the standard 'world saved' messages)
3+understand how the "/commandspy config" parameters work, and how to set it up.
4+understand how the "/commandspy filter" paramaters work, and how to set it up.
5+understand what every config.yml setting specifically does.


I'd assume the filter is per-player, but i don't understand how to use it.
also assume the config is global, but don't under stand it either.
-when I've tried to use those two it just doesn't like what i try to add. and without some examples to guide me, it's quite frustrating.

6.example of (correct this) setting up a config thingie:
/commandspy config ignore save-on
--doesn't work
7. filter example:
/commandspy filter set (i think?) ignore leasoncre
--actually have no idea what i'm supposed to do to set this up properly, but it's supposed to ignore my own commands
another filter:
8+how do i ignore all but 1 or several specific users?
9+can i ignore specific commands per-player and/or globally? (and how)

thanks

**Comment by EvelynSubarrow** [comment]
1: Not currently possible in either version, although this is one of the
eventual intentions of moving to rule lists
2: /commandspy filter add ignore (/)command (If preceded by a slash, it
will match only player commands, without,
it will only match server)
3: /commandspy config on its own should give you a list of parameter names.
Next to each will be listed the value. You should use /commandspy config
set name value
4: Again, /commandspy filter should give you a list of parameters you can
alter. In particular you should note that the flags have to be set to * to
do anything. considerFlags also needs to be set to true. In terms of design
this makes no sense at all. Regardless, when you use /commandspy on, this
is the result.
5: The config is intended to be modified in-game (or with the console)
using /commandspy config. Actually,  there's no way to reload the config,
making it somewhat impractical to do otherwise. For what it's worth, you're
right. The config file (and subcommand) relates to the plugin as a whole,
whereas filters relate to individual users (and the console, which is given
a null UUID for this purpose. Also a strange design decision, come to think
of it)
6: /commandspy config add ignore save-on
7: Ignores are only for commands, rather than users. This shortcoming will
be eventually addressed in the next release.
8: See above :/
9: /commandspy [config|filter] add ignore (/)command

2015-11-25 14:51 GMT+00:00 leasoncre <notifications@github.com>:

**Comment by leasoncre** [comment]
so confuseing. but i think i get it now.

what does signFlag do? 

some improvement ideas:
I1. add color to the output. ie: color the variable names, variable setting, and description differently. it helps make it easier to read.
I2. when a command's syntax is incorrect tell the user what the right syntax/subcommand is/are.
 -ie: "/commandspy filter signFlag *" says "subcommand not found".. so whats the right subcommand..


if you'd like to speak to me about helping develop/test this add me on skype or join teamspeak legendsandkings.typefarg.com

**Comment by EvelynSubarrow** [comment]
Version 4.0.0 was released. I'd appreciate feedback on the documentation, if you would be willing to spare the time

**Comment by leasoncre** [comment]
i already have. 

PS should redirect the 'ticket' button to here if you're not going to track tickets on bukkit.
http://dev.bukkit.org/bukkit-plugins/commandspy/tickets/17-initial-thoughts-on-v4/
